name: Generar y Publicar Feed

on:
  schedule:
    - cron: '0 0 * * *' # Se ejecuta a medianoche UTC cada 24 Horas
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Aseguramos que se instale desde el archivo
        
      - name: Ejecutar el script para generar el sitio estático
        run: python fetch_feeds.py
        
      - name: Desplegar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
